from src.cdcl.scratchpad import CDCLScratchpad
from src.model.parser import CommandParser
from src.cdcl.env import AutoregressiveCDCLEnvironment
from src.model.registry import CommandRegistry

import copy


def test_append_read_command(cfg, tokenizer):
    registry = CommandRegistry(cfg, tokenizer)
    scratchpad = CDCLScratchpad([], registry)
    parser = CommandParser(registry)
    env = AutoregressiveCDCLEnvironment(registry, scratchpad, parser)

    # Emit READ_ASSIGNMENTS
    token = registry.read_cmd_tokens["READ_ASSIGNMENTS"]
    env.append(token)

    # Check that token was appended
    assert token in env.get_current_input()
    # Check that a response (READ_BEGIN ... READ_END) was injected
    injected = env.get_current_input()
    assert registry.read_block_markers[0] in injected
    assert registry.read_block_markers[1] in injected


def test_append_write_command(cfg, tokenizer):
    registry = CommandRegistry(cfg, tokenizer)
    scratchpad = CDCLScratchpad([], registry)
    parser = CommandParser(registry)
    env = AutoregressiveCDCLEnvironment(registry, scratchpad, parser)

    def tok(s): return tokenizer.encode(s).ids

    tokens = [
        registry.write_cmd_tokens["WRITE_ASSIGNMENTS"],
        registry.write_block_markers[0],
        *tok("x1"),
        registry.write_block_markers[1],
    ]

    for t in tokens:
        env.append(t)

    history = env.get_current_input()
    history = copy.deepcopy(history)
    assert registry.read_block_markers[0] not in history

    env.append(registry.read_cmd_tokens["READ_ASSIGNMENTS"])
    new_history = env.get_current_input()
    # 3 new tokens should be added ['READ_ASSIGNMENTS', 'READ_BEGIN', 'x1', 'READ_END"]
    assert len(new_history) - len(history) == 4
    assert new_history[-1] == registry.read_block_markers[1]
    assert new_history[-2] == tok("x1")[0]
    assert new_history[-3] == registry.read_block_markers[0]
    assert new_history[-4] == registry.read_cmd_tokens["READ_ASSIGNMENTS"]


def test_unit_prop_stashing_and_restoring(cfg, tokenizer):
    registry = CommandRegistry(cfg, tokenizer)
    scratchpad = CDCLScratchpad([], registry)
    parser = CommandParser(registry)
    env = AutoregressiveCDCLEnvironment(registry, scratchpad, parser)

    token_before = tokenizer.token_to_id("x1")
    env.append(token_before)
    assert token_before in env.get_current_input()

    # Enter UNIT_PROP
    call_up = registry.action_cmd_tokens['CALL_UNIT_PROPAGATION']
    up_begin = registry.up_block_markers[0]
    env.append(call_up)
    assert token_before not in env.get_current_input()
    assert env.get_current_input() == [up_begin]

    # Add stuff inside
    t_inside = tokenizer.token_to_id("x2")
    env.append(t_inside)
    assert t_inside in env.get_current_input()

    # Exit UNIT_PROP
    up_end = registry.up_block_markers[1]
    env.append(up_end)

    # Should restore original history
    restored = env.get_current_input()
    assert token_before in restored
    assert up_begin not in restored
    assert call_up in restored
    assert t_inside not in restored


def test_finish_detection(cfg, tokenizer):
    registry = CommandRegistry(cfg, tokenizer)
    scratchpad = CDCLScratchpad([], registry)
    parser = CommandParser(registry)
    env = AutoregressiveCDCLEnvironment(registry, scratchpad, parser)

    end_tok = registry.solve_block_markers[1]
    assert not env.is_finished()

    env.append(end_tok)
    assert env.is_finished()


def test_optimal_predictor(cfg, tokenizer, tokenized_dataset):
    # Sample one structured trace
    sample = tokenized_dataset.sample_solve_traces(n=1)[0]

    # Build environment
    registry = CommandRegistry(cfg, tokenizer)
    scratchpad = CDCLScratchpad(sample.input_clauses['input_ids'], registry)
    parser = CommandParser(registry)
    env = AutoregressiveCDCLEnvironment(registry, scratchpad, parser)

    # We'll step through the solve trace, one token at a time
    solve_tokens = sample.solve["input_ids"]
    composed_tokens = sample.compose(
        up_call_token=registry.action_cmd_tokens["CALL_UNIT_PROPAGATION"],
        ac_call_token=registry.action_cmd_tokens["CALL_ANALYZE_CONFLICT"]
    )

    pos = 1  # skip the first token as it is generated by the environment
    env_pos = len(env.get_current_input())
    max_steps = 10000
    for step in range(max_steps):
        token = composed_tokens[pos] if pos < len(composed_tokens) else registry.pad_token
        if token == registry.up_block_markers[0] or token == registry.ac_block_markers[0]:
            # skip these tokens as they are generated by the environemnt
            pos += 1
            continue
        env.append(token)

        if env.is_finished():
            break
        
        prev_env_pos = env_pos
        if token == registry.up_block_markers[1] or token == registry.ac_block_markers[1]:
            # returning back to the solve context from either up or ac
            prev_env_pos = float("inf")  # so that the position goes up only by 1 this iteration
        env_pos = len(env.get_current_input())

        pos += max(1, env_pos - prev_env_pos)

        # if step > 180:
        #     print()
        #     print()
        #     print(tokenizer.decode(solve_tokens))
        #     print(len(sample.solve["input_ids"]))
        #     print(tokenizer.decode(sample.unit_propagation[2]['input_ids']))
        #     exit()

        # if step % 10 == 0:
        #     print('step:', step, 'pos:', pos, ' env_pos:', env_pos, ' prev_env_pos:', prev_env_pos, ' tok:', tokenizer.decode([token]))
        #     print(tokenizer.decode(env.get_current_input()))
        #     print()
    assert env.get_current_input() == solve_tokens
