defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

general:
  project: "SAT"
  devices: 1

tok_data:
  train_file: "../data/cdcl_dataset.json"
  tokenizer_path: "tokenizer/tokenizer.json"

data:
  datapath: data
  train_file_easy: "${data.datapath}/cdcl_easy_train.json"
  val_file_easy: "${data.datapath}/cdcl_easy_val.json"
  train_file_medium: "${data.datapath}/cdcl_medium_train.json"
  val_file_medium: "${data.datapath}/cdcl_medium_val.json"
  train_file_hard: "${data.datapath}/cdcl_hard_train.json"
  val_file_hard: "${data.datapath}/cdcl_hard_val.json"
  train_data: "hard"
  num_train: 100000
  num_eval: 1000
  num_workers: 64

model:
  name: "Pythia-${model.n_layer}-${model.n_head}-${model.n_embd}"
  batch_size: 128
  accumulate_grad_batches: 1
  block_size: 4096
  epochs: 200
  n_layer: 12
  n_head: 8
  n_embd: 512
  vocab_size: 66
  padded_vocab_size: 68
  bos_id: 62
  eos_id: 66

optimizer:
  warmup_steps: 1000
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]

eval:
  num_examples: 128
  batch_size: 64
  eval_interval: 10
  results_dir: "data/eval_results/${model.name}"
  log_step_frequency: 50
  val_check_interval: 0.2
  callback_epoch_frequency: 1
  callback_acc_data_count: 100

convert_hf:
  in_path: "temp/${model.name}"
  out_path: "temp/hf_${model.name}"